# Generated by Django 5.1.3 on 2024-12-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('La', 'Laptop'), ('Mo', 'Mobile'), ('Tab', 'Tablet'), ('TV', 'TV'), ('Ga', 'Gaming'), ('App', 'Appliance'), ('Ac', 'Accessories')], max_length=5),
        ),
    ]
