# Generated by Django 5.1.3 on 2024-12-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_on',
        ),
    ]
